spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: Gold_Rush_Lab_Consumer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/goldrush}
    username: ${POSTGRES_USER:goldrush}
    password: ${POSTGRES_PASSWORD:goldrush}
    hikari:
      maximum-pool-size: ${DB_CONNECTION_POOL_SIZE:20}

  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: gold-rush-mining-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
