spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: Gold-Rush-Lab

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    name: ${POSTGRES_DB}

  jpa:
    generate-ddl: false

server:
  port: 8080
  servlet:
    context-path: "/api"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
