include:
  - ../infra/db/compose.yml
  - ../infra/loadbalancer/compose.yml
  - ../infra/monitoring/compose.yml

services:
  gold-rush-app:
    image: ghcr.io/yeoooo/gold-rush-lab:${APP_IMAGE_TAG:-v0.1}
    profiles:
      - container
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-goldrush}
      POSTGRES_DB: ${POSTGRES_DB:-goldrush}
      POSTGRES_USER: ${POSTGRES_USER:-goldrush}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_CONNECTION_POOL_SIZE: ${DB_CONNECTION_POOL_SIZE:-50}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - goldrush-db-network
